language: csharp
solution: Myriagonal.Net.sln
install:
  - nuget restore Myriagonal.Net.sln
  - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Myriagonal.Net.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./Myriagonal.Net.Tests/bin/Release/Myriagonal.Net.Tests.dll
